### PR TITLE
basic html framework for index.html

### PR DESCRIPTION
**Pull request by annblodgett**
Created a basic skeleton for the index page. No styling. A place to start :)

### CODE REVIEW

**Comment by briancbarrow** [comment]
I have no problem with this. @alvaro911, you were going to work on the homepage. What do you think?

Thanks @annblodgett for contributing!!

**Comment by alvaro911** [comment]
It's a really good start, thank you @annblodgett

**Comment by annblodgett** [comment]
Thanks! I appreciate you guys taking time to look at the suggestions! 👍  Is there somewhere to sign up/ look at the pieces that still need work? If not are there any other projects in the mix?

**Comment by annblodgett** [comment]
As you can tell I'm pretty excited by the whole FCC thing ;)

**Comment by alvaro911** [comment]
Cool, so will you be assisting to the meetup this saturday or the following one?

**Comment by briancbarrow** [comment]
If you come to the meetups we'll be talking about other things we can do.

**Comment by annblodgett** [comment]
Awesome! I've got them both on my calendar - guess I'll see you all Saturday :)

**Pull request merged**
